ERROR    services.city_service:city_service.py:49 Город с ID 123 не найден.