ERROR    services.directory_route_service:directory_route_service.py:40 Справочник маршрутов с ID 1 не найден.