ERROR    services.travel_service:travel_service.py:110 Ошибка при связывании пользователей [1, 2, 3] с путешествием 1