{"uid":"ee440ff7c1008ba8","name":"test_login_and_add_city_api","fullName":"tests.e2e.test_add_city_e2e.TestAuthenticationE2ESimple#test_login_and_add_city_api","historyId":"b5839d32e8b1cbc0fbbd3db579313549","time":{"start":1758903186283,"stop":1758903186372,"duration":89},"status":"broken","statusMessage":"httpx.ConnectError: [Errno -3] Temporary failure in name resolution","statusTrace":"@contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n>           yield\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:72: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:377: in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection_pool.py:256: in handle_async_request\n    raise exc from None\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection_pool.py:236: in handle_async_request\n    response = await connection.handle_async_request(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:101: in handle_async_request\n    raise exc\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:78: in handle_async_request\n    stream = await self._connect(request)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:124: in _connect\n    stream = await self._network_backend.connect_tcp(**kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_backends/auto.py:31: in connect_tcp\n    return await self._backend.connect_tcp(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_backends/anyio.py:113: in connect_tcp\n    with map_exceptions(exc_map):\n         ^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nmap = {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'OSError'>: <class 'httpcore.ConnectError'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ConnectError'>}\n\n    @contextlib.contextmanager\n    def map_exceptions(map: ExceptionMapping) -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:  # noqa: PIE786\n            for from_exc, to_exc in map.items():\n                if isinstance(exc, from_exc):\n>                   raise to_exc(exc) from exc\nE                   httpcore.ConnectError: [Errno -3] Temporary failure in name resolution\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_exceptions.py:14: ConnectError\n\nThe above exception was the direct cause of the following exception:\n\nself = <test_add_city_e2e.TestAuthenticationE2ESimple object at 0x7ff522d9ead0>\n\n    @pytest.mark.asyncio\n    async def test_login_and_add_city_api(self):\n        async with httpx.AsyncClient(base_url=\"http://app:8000\") as client:\n            with allure.step(\"Prepare login data\"):\n                login_data = {\"login\": \"admin1\", \"password\": \"123!e5T78\"}\n    \n            with allure.step(\"Send login request\"):\n>               resp = await client.post(\"/api/login\", json=login_data)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntests/e2e/test_add_city_e2e.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1905: in post\n    return await self.request(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1585: in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1674: in send\n    response = await self._send_handling_auth(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1702: in _send_handling_auth\n    response = await self._send_handling_redirects(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1739: in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1776: in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:376: in handle_async_request\n    with map_httpcore_exceptions():\n         ^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:\n            mapped_exc = None\n    \n            for from_exc, to_exc in HTTPCORE_EXC_MAP.items():\n                if not isinstance(exc, from_exc):\n                    continue\n                # We want to map to the most specific exception we can find.\n                # Eg if `exc` is an `httpcore.ReadTimeout`, we want to map to\n                # `httpx.ReadTimeout`, not just `httpx.TimeoutException`.\n                if mapped_exc is None or issubclass(to_exc, mapped_exc):\n                    mapped_exc = to_exc\n    \n            if mapped_exc is None:  # pragma: no cover\n                raise\n    \n            message = str(exc)\n>           raise mapped_exc(message) from exc\nE           httpx.ConnectError: [Errno -3] Temporary failure in name resolution\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:89: ConnectError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1758903186215,"stop":1758903186215,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1758903186215,"stop":1758903186215,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1758903186215,"stop":1758903186281,"duration":66},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1758903186281,"stop":1758903186281,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1758903186281,"stop":1758903186281,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop_policy","time":{"start":1758903186282,"stop":1758903186282,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1758903186282,"stop":1758903186283,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_event_loop","time":{"start":1758903186282,"stop":1758903186282,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"httpx.ConnectError: [Errno -3] Temporary failure in name resolution","statusTrace":"@contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n>           yield\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:72: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:377: in handle_async_request\n    resp = await self._pool.handle_async_request(req)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection_pool.py:256: in handle_async_request\n    raise exc from None\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection_pool.py:236: in handle_async_request\n    response = await connection.handle_async_request(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:101: in handle_async_request\n    raise exc\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:78: in handle_async_request\n    stream = await self._connect(request)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_async/connection.py:124: in _connect\n    stream = await self._network_backend.connect_tcp(**kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_backends/auto.py:31: in connect_tcp\n    return await self._backend.connect_tcp(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_backends/anyio.py:113: in connect_tcp\n    with map_exceptions(exc_map):\n         ^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nmap = {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'OSError'>: <class 'httpcore.ConnectError'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ConnectError'>}\n\n    @contextlib.contextmanager\n    def map_exceptions(map: ExceptionMapping) -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:  # noqa: PIE786\n            for from_exc, to_exc in map.items():\n                if isinstance(exc, from_exc):\n>                   raise to_exc(exc) from exc\nE                   httpcore.ConnectError: [Errno -3] Temporary failure in name resolution\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpcore/_exceptions.py:14: ConnectError\n\nThe above exception was the direct cause of the following exception:\n\nself = <test_add_city_e2e.TestAuthenticationE2ESimple object at 0x7ff522d9ead0>\n\n    @pytest.mark.asyncio\n    async def test_login_and_add_city_api(self):\n        async with httpx.AsyncClient(base_url=\"http://app:8000\") as client:\n            with allure.step(\"Prepare login data\"):\n                login_data = {\"login\": \"admin1\", \"password\": \"123!e5T78\"}\n    \n            with allure.step(\"Send login request\"):\n>               resp = await client.post(\"/api/login\", json=login_data)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntests/e2e/test_add_city_e2e.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1905: in post\n    return await self.request(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1585: in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1674: in send\n    response = await self._send_handling_auth(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1702: in _send_handling_auth\n    response = await self._send_handling_redirects(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1739: in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py:1776: in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:376: in handle_async_request\n    with map_httpcore_exceptions():\n         ^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:\n            mapped_exc = None\n    \n            for from_exc, to_exc in HTTPCORE_EXC_MAP.items():\n                if not isinstance(exc, from_exc):\n                    continue\n                # We want to map to the most specific exception we can find.\n                # Eg if `exc` is an `httpcore.ReadTimeout`, we want to map to\n                # `httpx.ReadTimeout`, not just `httpx.TimeoutException`.\n                if mapped_exc is None or issubclass(to_exc, mapped_exc):\n                    mapped_exc = to_exc\n    \n            if mapped_exc is None:  # pragma: no cover\n                raise\n    \n            message = str(exc)\n>           raise mapped_exc(message) from exc\nE           httpx.ConnectError: [Errno -3] Temporary failure in name resolution\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py:89: ConnectError","steps":[{"name":"Prepare login data","time":{"start":1758903186306,"stop":1758903186306,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Send login request","time":{"start":1758903186306,"stop":1758903186369,"duration":63},"status":"broken","statusMessage":"httpx.ConnectError: [Errno -3] Temporary failure in name resolution\n","statusTrace":"  File \"/home/runner/work/Testing_and_debbug/Testing_and_debbug/tests/e2e/test_add_city_e2e.py\", line 20, in test_login_and_add_city_api\n    resp = await client.post(\"/api/login\", json=login_data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1905, in post\n    return await self.request(\n           ^^^^^^^^^^^^^^^^^^^\n    ...<13 lines>...\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1585, in request\n    return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1674, in send\n    response = await self._send_handling_auth(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<4 lines>...\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1702, in _send_handling_auth\n    response = await self._send_handling_redirects(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1739, in _send_handling_redirects\n    response = await self._send_single_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_client.py\", line 1776, in _send_single_request\n    response = await transport.handle_async_request(request)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py\", line 376, in handle_async_request\n    with map_httpcore_exceptions():\n         ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/httpx/_transports/default.py\", line 89, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"event_loop::finalizer","time":{"start":1758903186531,"stop":1758903186532,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1758903186532,"stop":1758903186532,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_restore_policy","time":{"start":1758903186532,"stop":1758903186532,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1758903186532,"stop":1758903186532,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_event_loop::0","time":{"start":1758903186533,"stop":1758903186533,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"E2E Authentication API"},{"name":"story","value":"User Authentication Flow"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.e2e"},{"name":"suite","value":"test_add_city_e2e"},{"name":"subSuite","value":"TestAuthenticationE2ESimple"},{"name":"host","value":"runnervm3ublj"},{"name":"thread","value":"2746-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.e2e.test_add_city_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["asyncio"]},"source":"ee440ff7c1008ba8.json","parameterValues":[]}